spring.application.name=pequenoavionAB
server.port=9191

# Configuraci\u00f3n de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/pequeno_avion_db
spring.datasource.username=javier
spring.datasource.password=campusjalpa
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Configuraci\u00f3n de JPA/Hibernate
# OJO: Usamos 'validate' o 'none' porque ya se creo las tablas en SQL.
# No queremos que Spring las borre o modifique.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect